"""Generate Dashboard.md with tables and mermaid charts."""
from __future__ import annotations

from collections import Counter
from pathlib import Path

from .indexer import IndexedPaper, iter_papers
from .writer import resolve_content_root


def _status_counts(papers: list[IndexedPaper]) -> Counter:
    c: Counter = Counter()
    for p in papers:
        c[p.meta.get("status", "todo")] += 1
    for key in ("todo", "reading", "done", "abandoned"):
        c.setdefault(key, 0)
    return c


def render_dashboard(papers: list[IndexedPaper]) -> str:
    total = len(papers)
    counts = _status_counts(papers)
    years = Counter(str(p.meta.get("year", "unknown"))[:4] for p in papers)

    # mermaid pie needs at least one non-zero; use placeholder 1 for empty
    pie_parts = []
    for key in ("todo", "reading", "done", "abandoned"):
        val = counts[key]
        if total == 0 and key == "todo":
            val = 1
        if val > 0:
            pie_parts.append(f'  "{key}" : {val}')

    year_rows = [
        f"| {y} | {n} |" for y, n in sorted(years.items(), reverse=True)
    ] or ["| — | 0 |"]

    recent = papers[-10:][::-1]
    recent_rows = []
    for p in recent:
        m = p.meta
        recent_rows.append(
            f"| {m.get('started_at') or m.get('finished_at') or '—'} | {m.get('title', p.path.stem)} | {m.get('status', 'todo')} |"
        )
    if not recent_rows:
        recent_rows = ["| — | — | — |"]

    lines = [
        "# Reading Dashboard",
        "",
        "Generated by **wiki-bridge**. Regenerate with `rebuild-index`.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|------:|",
        f"| Total papers | {total} |",
        f"| todo | {counts['todo']} |",
        f"| reading | {counts['reading']} |",
        f"| done | {counts['done']} |",
        f"| abandoned | {counts['abandoned']} |",
        "",
        "<!-- BRIDGE:DASHBOARD_SUMMARY -->",
        "",
        "## By status",
        "",
        "```mermaid",
        "pie title Reading status",
        *pie_parts,
        "```",
        "",
        "<!-- BRIDGE:DASHBOARD_STATUS_PIE -->",
        "",
        "## By year",
        "",
        "| Year | Count |",
        "|------|------:|",
        *year_rows,
        "",
        "<!-- BRIDGE:DASHBOARD_YEAR_TABLE -->",
        "",
        "## Recent updates",
        "",
        "| Date | Title | Status |",
        "|------|-------|--------|",
        *recent_rows,
        "",
        "<!-- BRIDGE:DASHBOARD_RECENT -->",
        "",
    ]
    return "\n".join(lines)


def write_dashboard(content_root: Path) -> Path:
    root = resolve_content_root(content_root)
    papers = iter_papers(root)
    path = root / "_meta" / "Dashboard.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_dashboard(papers), encoding="utf-8")
    return path
